#!/bin/sh
ver=`cat version.txt | tr -d "\r"`
echo Version "$ver"
dist=dist
distdir=${dist}/GaussSum-$ver
source=src
img=logo
docs=docs
here=`pwd`

# rm -fr $dist
mkdir -p $dist

######################### XP source

echo Creating the XP source distribution...
rm -rf $distdir
mkdir $distdir

cp $source/*.py $distdir

mkdir $distdir/gausssum
cp $source/gausssum/*.py $source/gausssum/*.gif $distdir/gausssum
mkdir $distdir/gausssum/cclib
mkdir $distdir/gausssum/cclib/parser
cp $source/gausssum/cclib/*.py $distdir/gausssum/cclib
cp $source/gausssum/cclib/parser/*.py $distdir/gausssum/cclib/parser

cp -r $source/gnuplot460 $distdir
cp $img/*.ico $img/*.gif $distdir

mkdir $distdir/Docs
cp $docs/*.html $docs/*.gif $docs/*.css $distdir/Docs

cd $dist
/cygdrive/c/Program\ Files/7-Zip/7z a -tzip -r -mx=9 GaussSum-${ver}.zip GaussSum-${ver} -ir\!GaussSum-${ver}/* > /dev/null
cd ..
rm -rf $distdir
